package Terceros;


/**
* Terceros/Tercero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Terceros.idl
* miércoles 26 de septiembre de 2018 09:16:19 PM COT
*/

public interface Tercero extends TerceroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Tercero
